import 'image_and_background_product_brand_list_item_controller_state.dart';

class HorizontalImageAndBackgroundProductBrandListItemControllerState extends ImageAndBackgroundProductBrandListItemControllerState {
  HorizontalImageAndBackgroundProductBrandListItemControllerState({
    required super.productBrand
  });
}